name: easy_auth
description: Easy authentication for Flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  formz: ^0.4.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  google_sign_in: ^5.4.2
  meta: ^1.8.0
  flutter_bloc: ^8.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
