name: easy_auth
description: Easy authentication for Flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  formz: ^0.4.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  google_sign_in: ^5.2.4
  meta: ^1.7.0
  flutter_bloc: ^8.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
